### ISSUE TITLE
Virtual terminal implementation and Upp/TerminalCtrl

### ISSUE THREAD

**Issue by ismail-yilmaz** [chivstyle/comxd#1]
Hello chivsyle,

I was watching for some time this nice little tool mature step by step.

And I am wondering if there is any specific reason why you're not using TerminalCtrl for virtual terminal?.

Now, don't get me wrong, I am asking this because;

- I can improve it, if it is not sufficient for your needs. (i.e. feedbacks are always welcome)
- I can help you if you really need to implement one yourself.

Best regards,

**Comment by chivstyle** [comment]
Hi,

TerminalCtrl is really handsome. I used it before, I almost given up my terminal.

As you seen, this tool (comxd) was designed to run on Windows. I found some bugs of TerminalCtrl on Windows, and you fixed them immediately. However it's not the reason I reimplement a terminal.

- I want unlimited line size
- I want arbitary line height (not fixed height)
- I want to limit the features of terminal
- I want full unicode
- A command "yes" maybe make TerminalCtrl in trouble
- I expect better performance than mintty

Of course, it's not the responsibility of TerminalCtrl to implement them all. But I'm a freshman that day about virtual terminal, I'm so sorry to make a mistake to TerminalCtrl.

It takes me so long time to make it usable, only usable for this application. There MUST be bugs anywhere, it's freaking bad.

I'll test TerminalCtrl later, if it's better than mintty and kicked the "yes" away, I think TerminalCtrl is the first choice.

My english sucks, can you understand what I said please ?

Best regards.

**Comment by ismail-yilmaz** [comment]
Hi

Thank you very much for you response.

> My english sucks, can you understand what I said please ?

Don't worry, I can understand you. My English is far from being perfect, too. :)

> I want full unicode

Do you mean graphemes? Because TerminalCtrl supports what U++ supports in this front. U++ now supports 32 bit wchars, so TerminalCtrl can even display colored emojis now. (Again, no grapheme support yet).

> A command "yes" maybe make TerminalCtrl in trouble

Hmm. On POSIX or Windows? I'd really love to investigate this further.  And I'd be grateful if you could provide a specific example that cam "trouble" TerminalCtrl.

> I expect better performance than mintty

Well, this is complicated. Have you tried the TerminalLayoutExample or just TerminalExample? Because the latter is delberately made slower. The former (TerminalLayoutExample), on the other hand, exemplifies a high-performance loop for production environments. (performance diff between the two stock examples I provided with the package are huge). 

> I want to limit the features of terminal

This is already possible. Boolean methods just do that. (E.g. you can completely disable the features you don't need, such as sixel, dynamic colors, etc.)

> - I want unlimited line size
> - I want arbitary line height (not fixed height)

Well, if by "arbitrary height" you mean cell level arbitrariness, yes it is fixed. But the font size and padding can be changed at request.

>  I'm so sorry to make a mistake to TerminalCtrl.

Ah, there is nothing to be sorry about, I'm asking these questions to see (a) if I can help you, (b) get some feedback on TerminalCtrl. Thank you very much for you patience and answers.

If you need help on VT emulation or SSH (as I am the author of SSH package too), let me know.

Best regards,

**Comment by chivstyle** [comment]
>A command "yes" maybe make TerminalCtrl in trouble.

A linux internal command "yes" will output large count of "y" which results in corruption at some version.

>- I want unlimited line size
>- I want arbitary line height(not fixed height)

It's not the problem now. We don't need these features anymore.

>I want full unicode

Yes, you are right. UPP supports full unicode now.

>I expect better performance than mintty

The latest TerminalCtrl runs as I expected.

I have tested the latest TerminalCtrl. It's amazing, and I have no reason to do not use it. Thanks for your great work, this project will benefit from that.

Best regards.

**Comment by chivstyle** [comment]
:smile:
