### ISSUE TITLE
Installation and build instruction is needed.

### ISSUE THREAD

**Issue by ismail-yilmaz** [chivstyle/comxd#2]
One problem I see with comxd is tha it is not clear how to "wire" it and get it work.
Since this is an app, IMHO it'll be better off with installation and build instructions.

Best regards,

**Comment by chivstyle** [comment]
Thanks for your advise, I'll add more documents to show the features of this tool.

Best regards.

**Comment by ismail-yilmaz** [comment]
@chivstyle 

Just to "show off" your nice little tool. :)

![image](https://user-images.githubusercontent.com/32938453/195995291-b9f48dee-8413-4364-a5f1-bdcdb0ae2c93.png)

**Comment by chivstyle** [comment]
It looks pretty good.
